# Generated by Django 4.0.6 on 2022-10-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reister',
            old_name='email',
            new_name='emails',
        ),
    ]
