# Generated by Django 4.0.6 on 2022-10-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_reister_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
